-- apply changes
create table reports (
  id                            bigint generated by default as identity not null,
  target_type                   integer not null,
  target_id                     bigint not null,
  reporter_id                   bigint,
  reason                        integer not null,
  status                        integer not null,
  creation_date                 timestamp not null,
  resolution_date               timestamp,
  resolved_by_id                bigint,
  resolution                    integer,
  comment                       varchar(1023) default '' not null,
  moderator_note                varchar(1023) default '' not null,
  constraint ck_reports_target_type check ( target_type in (0,1,2)),
  constraint ck_reports_reason check ( reason in (0,1,2,3,4,5)),
  constraint ck_reports_status check ( status in (0,1,2)),
  constraint ck_reports_resolution check ( resolution in (0,1,2,3,4)),
  constraint pk_reports primary key (id)
);

-- apply alter tables
alter table recipes add column if not exists is_hidden boolean default false not null;
alter table recipes add column if not exists hidden_reason varchar(1023) default '' not null;
alter table users add column if not exists is_banned boolean default false not null;
alter table users add column if not exists suspended_until timestamp;
alter table users add column if not exists moderation_note varchar(1023) default '' not null;
-- foreign keys and indices
create index ix_reports_reporter_id on reports (reporter_id);
alter table reports add constraint fk_reports_reporter_id foreign key (reporter_id) references users (id) on delete restrict on update restrict;

create index ix_reports_resolved_by_id on reports (resolved_by_id);
alter table reports add constraint fk_reports_resolved_by_id foreign key (resolved_by_id) references users (id) on delete restrict on update restrict;

