-- apply changes
create table pdf_templates (
  id                            bigint generated by default as identity not null,
  locale                        integer not null,
  updated_at                    timestamp not null,
  document_key                  varchar(63) not null,
  body                          varchar(65535) not null,
  constraint ck_pdf_templates_locale check ( locale in (0,1)),
  constraint uq_pdf_templates_document_key_locale unique (document_key,locale),
  constraint pk_pdf_templates primary key (id)
);

