-- apply changes
create table devices (
  id                            bigint generated by default as identity not null,
  user_id                       bigint not null,
  platform                      integer not null,
  locale                        integer not null,
  created_at                    timestamp not null,
  last_seen_at                  timestamp not null,
  token                         varchar(4095) not null,
  constraint ck_devices_platform check ( platform in (0,1,2)),
  constraint ck_devices_locale check ( locale in (0,1)),
  constraint uq_devices_token unique (token),
  constraint pk_devices primary key (id)
);

create table notifications (
  id                            bigint generated by default as identity not null,
  user_id                       bigint not null,
  kind                          integer not null,
  actor_id                      bigint,
  created_at                    timestamp not null,
  read_at                       timestamp,
  title                         varchar(127) not null,
  body                          varchar(511) not null,
  link                          varchar(511) default '' not null,
  constraint ck_notifications_kind check ( kind in (0,1,2,3,4)),
  constraint pk_notifications primary key (id)
);

-- foreign keys and indices
create index ix_devices_user_id on devices (user_id);
alter table devices add constraint fk_devices_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

create index ix_notifications_user_id on notifications (user_id);
alter table notifications add constraint fk_notifications_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

create index ix_notifications_actor_id on notifications (actor_id);
alter table notifications add constraint fk_notifications_actor_id foreign key (actor_id) references users (id) on delete restrict on update restrict;

