-- apply changes
create table app_versions (
  id                            bigint generated by default as identity not null,
  platform                      integer not null,
  updated_at                    timestamp not null,
  minimum_version               varchar(23) not null,
  latest_version                varchar(23) not null,
  store_url                     varchar(511) not null,
  constraint ck_app_versions_platform check ( platform in (0,1)),
  constraint uq_app_versions_platform unique (platform),
  constraint pk_app_versions primary key (id)
);

