-- apply changes
create table oauth_clients (
  id                            bigint generated by default as identity not null,
  registered_at                 timestamp not null,
  last_used_at                  timestamp not null,
  client_id                     varchar(64) not null,
  client_name                   varchar(255) not null,
  constraint uq_oauth_clients_client_id unique (client_id),
  constraint pk_oauth_clients primary key (id)
);

create table oauth_clients_redirect_uris (
  oauth_clients_id              bigint not null,
  value                         varchar not null
);

-- foreign keys and indices
create index ix_oauth_clients_redirect_uris_oauth_clients_id on oauth_clients_redirect_uris (oauth_clients_id);
alter table oauth_clients_redirect_uris add constraint fk_oauth_clients_redirect_uris_oauth_clients_id foreign key (oauth_clients_id) references oauth_clients (id) on delete restrict on update restrict;

