-- apply changes
create table oauth_grants (
  id                            bigint generated by default as identity not null,
  user_id                       bigint not null,
  client_id                     varchar(64) not null,
  granted_at                    timestamp not null,
  last_used_at                  timestamp not null,
  constraint uq_oauth_grants_user_id_client_id unique (user_id,client_id),
  constraint pk_oauth_grants primary key (id)
);

-- foreign keys and indices
create index ix_oauth_grants_user_id on oauth_grants (user_id);
alter table oauth_grants add constraint fk_oauth_grants_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;
