-- drop dependencies
alter table if exists recipes_steps drop constraint if exists fk_recipes_steps_recipes_id;
-- apply changes
create table recipe_steps (
  id                            bigint generated by default as identity not null,
  recipe_id                     bigint,
  duration_seconds              integer,
  sort_order                    integer default 0 not null,
  text                          varchar(255) not null,
  constraint pk_recipe_steps primary key (id)
);

-- foreign keys and indices
create index ix_recipe_steps_recipe_id on recipe_steps (recipe_id);
alter table recipe_steps add constraint fk_recipe_steps_recipe_id foreign key (recipe_id) references recipes (id) on delete restrict on update restrict;


-- Carry the existing steps over. Ebean generates the table but knows nothing about what was
-- in the one it replaces, so this is by hand.
--
-- The order is the awkward part, and the reason the new table exists: `recipes_steps` was an
-- element collection and had no sort column at all. It relied on rows coming back in the
-- order they were written, which Ebean did by deleting every row and re-inserting the whole
-- list on each save. Physical order is therefore the only record of the author's order there
-- has ever been, and `ctid` is the only way to read it. It is not a guarantee the database
-- makes -- a VACUUM FULL would rewrite it -- but these rows are never UPDATEd, only deleted
-- and re-inserted, so it is what the last save left behind.
--
-- Durations start null: the column did not exist before this, so no step has ever had one.
insert into recipe_steps (recipe_id, text, duration_seconds, sort_order)
select recipes_id,
       value,
       null,
       (row_number() over (partition by recipes_id order by ctid))::int - 1
from recipes_steps;

-- `recipes_steps` is deliberately left standing. Ebean defers table drops to a later
-- `__dropsFor_` migration by design -- there are already pending ones from 1.34 and 1.36 --
-- and here that deferral is worth having for its own sake: until it is dropped, the old
-- steps are still on disk and this migration can be undone.
