-- apply changes
create table recipe_step_ingredients (
  id                            bigint generated by default as identity not null,
  step_id                       bigint,
  ingredient_id                 bigint,
  amount                        float,
  constraint pk_recipe_step_ingredients primary key (id)
);

-- foreign keys and indices
create index ix_recipe_step_ingredients_step_id on recipe_step_ingredients (step_id);
alter table recipe_step_ingredients add constraint fk_recipe_step_ingredients_step_id foreign key (step_id) references recipe_steps (id) on delete restrict on update restrict;

create index ix_recipe_step_ingredients_ingredient_id on recipe_step_ingredients (ingredient_id);
alter table recipe_step_ingredients add constraint fk_recipe_step_ingredients_ingredient_id foreign key (ingredient_id) references recipe_ingredients (id) on delete restrict on update restrict;

