-- apply changes
create table ai_settings (
  id                            bigint generated by default as identity not null,
  daily_limit_per_user          integer not null,
  updated_at                    timestamp not null,
  monthly_budget                decimal(12,2),
  input_price_per_million       decimal(12,6) not null,
  output_price_per_million      decimal(12,6) not null,
  currency                      varchar(3) not null,
  constraint pk_ai_settings primary key (id)
);

create table ai_usage (
  id                            bigint generated by default as identity not null,
  user_id                       bigint,
  created_at                    timestamp not null,
  feature                       integer not null,
  pages                         integer not null,
  input_tokens                  integer,
  output_tokens                 integer,
  outcome                       integer not null,
  cost                          decimal(14,6) not null,
  model                         varchar(255) not null,
  constraint ck_ai_usage_feature check ( feature in (0)),
  constraint ck_ai_usage_outcome check ( outcome in (0,1,2)),
  constraint pk_ai_usage primary key (id)
);

-- foreign keys and indices
create index ix_ai_usage_user_id on ai_usage (user_id);
alter table ai_usage add constraint fk_ai_usage_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

create index if not exists ix_ai_usage_created_at on ai_usage (created_at);
