-- apply changes
create table photo_imports (
  id                            bigint generated by default as identity not null,
  user_id                       bigint,
  created_at                    timestamp not null,
  pages                         integer not null,
  input_tokens                  integer,
  output_tokens                 integer,
  outcome                       integer not null,
  cost                          decimal(14,6) not null,
  model                         varchar(255) not null,
  constraint ck_photo_imports_outcome check ( outcome in (0,1,2)),
  constraint pk_photo_imports primary key (id)
);

create table photo_import_settings (
  id                            bigint generated by default as identity not null,
  daily_limit_per_user          integer not null,
  updated_at                    timestamp not null,
  monthly_budget                decimal(12,2),
  input_price_per_million       decimal(12,6) not null,
  output_price_per_million      decimal(12,6) not null,
  currency                      varchar(3) not null,
  constraint pk_photo_import_settings primary key (id)
);

-- foreign keys and indices
create index ix_photo_imports_user_id on photo_imports (user_id);
alter table photo_imports add constraint fk_photo_imports_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

create index if not exists ix_photo_imports_created_at on photo_imports (created_at);
