-- apply changes
create table meal_plan_entries (
  id                            bigint generated by default as identity not null,
  owner_id                      bigint not null,
  date                          date not null,
  position                      integer not null,
  recipe_id                     bigint,
  servings                      integer,
  slot                          varchar(16) not null,
  title                         varchar(255) not null,
  constraint ck_meal_plan_entries_slot check ( slot in ('BREAKFAST','LUNCH','SNACK','DINNER')),
  constraint pk_meal_plan_entries primary key (id)
);

-- foreign keys and indices
create index ix_meal_plan_entries_owner_id on meal_plan_entries (owner_id);
alter table meal_plan_entries add constraint fk_meal_plan_entries_owner_id foreign key (owner_id) references users (id) on delete restrict on update restrict;

create index ix_meal_plan_entries_recipe_id on meal_plan_entries (recipe_id);
alter table meal_plan_entries add constraint fk_meal_plan_entries_recipe_id foreign key (recipe_id) references recipes (id) on delete set null on update restrict;

create index if not exists ix_meal_plan_entries_owner_id_date on meal_plan_entries (owner_id,date);
