-- apply changes
create table email_templates (
  id                            bigint generated by default as identity not null,
  locale                        integer not null,
  mail_key                      varchar(63) not null,
  subject                       varchar(255) not null,
  body                          varchar(16383) not null,
  constraint ck_email_templates_locale check ( locale in (0,1)),
  constraint uq_email_templates_mail_key_locale unique (mail_key,locale),
  constraint pk_email_templates primary key (id)
);

